enc_test: mfc_enc_test_mp4.c mfc_enc_test_264.c enc/src/SsbSipMfcEncAPI.c include/SsbSipMfcApi.h include/mfc_interface.h include/log.h
	arm-linux-gcc -Iinclude -o enc_test_264 mfc_enc_test_264.c enc/src/SsbSipMfcEncAPI.c
	arm-linux-gcc -Iinclude -o enc_test_mp4 mfc_enc_test_mp4.c enc/src/SsbSipMfcEncAPI.c
